import type { Metadata } from "next";
import {
  Inter,
  Montserrat
} from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
// import localFont from 'next/font/local'

// const myFont = localFont({ src: '/fonts/Helvetica.ttf' })


const inter = Inter({ subsets: ["latin"] });

const montressat = Montserrat({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AiSensy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${montressat.className} bg-white`}>
      <Header />
      <div className=''>
        {children}
      </div>
      <Footer/>
    </body>
  </html>
  );
}
